//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Material.Domain.Credentials;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using Material.Framework.Enums;
using Material.Framework.Metadata;
using Material.Domain.Core;

namespace Material.Domain.ResourceProviders
{     
    /// <summary>
    /// Login with Amazon v1.0
    /// </summary>
    [CredentialType(typeof(OAuth2Credentials))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class Amazon  : OAuth2ResourceProvider 
    {
        public override List<string> AvailableScopes { get; } = new List<string> { "profile", "profile:user_id", "postal_code", "alexa:all" };
        public override List<OAuth2FlowType> AllowedFlows { get; } = new List<OAuth2FlowType> { OAuth2FlowType.Implicit, OAuth2FlowType.AccessCode };
        public override List<GrantType> AllowedGrantTypes { get; } = new List<GrantType> { GrantType.AuthCode, GrantType.RefreshToken };
        public override List<OAuth2ResponseType> AllowedResponseTypes { get; } = new List<OAuth2ResponseType> { OAuth2ResponseType.Token, OAuth2ResponseType.Code };
        public override string TokenName { get; } = "access_token";
        public override Uri AuthorizationUrl { get; } = new Uri("https://www.amazon.com/ap/oa");
        public override Uri TokenUrl { get; } = new Uri("https://api.amazon.com/auth/o2/token");
        public override bool SupportsPkce { get; } = true;
        public override bool SupportsCustomUrlScheme { get; } = true;
        public override char ScopeDelimiter { get; } = ' ';
    }
}
