{
    "swagger": "2.0",
    "info": {
        "title": "Youtube",
        "description": "Youtube API",
        "termsOfService": "https://developers.google.com/youtube/terms/api-services-terms-of-service",
        "version": "1"
    },
    "host": "www.googleapis.com",
    "basePath": "/youtube",
    "schemes": [ "https" ],
    "paths": {
        "/analytics/v1/reports": {
            "get": {
                "summary": "Retrieves a YouTube Analytics report",
                "description": "https://developers.google.com/youtube/analytics/v1/reference/reports/query",
                "operationId": "YoutubeAnalyticsReports",
                "tags": [],
                "security": [
                    {
                        "oauth2": [ "https://www.googleapis.com/auth/yt-analytics.readonly" ]
                    }
                ]
            }
        },
        "/v3/channels": {
            "get": {
                "summary": "Returns a collection of zero or more channel resources that match the request criteria",
                "description": "https://developers.google.com/youtube/v3/docs/channels/list",
                "operationId": "YoutubeChannels",
                "tags": [],
                "security": [
                    {
                        "oauth2": [ "https://www.googleapis.com/auth/youtube" ]
                    }
                ]
            }
        }
    },
    "securityDefinitions": {
        "oauth2Code": {
            "type": "oauth2",
            "description": "OAuth2 Access Code Grant",
            "flow": "accessCode",
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "tokenUrl": "https://accounts.google.com/o/oauth2/token",
            "name": "access_token",
            "in": "header",
            "x-grant-types": [ "authorization_code", "refresh_token" ],
            "x-response-types": [ "code" ],
            "x-pkce-support": true,
            "scopes": {
                "https://www.googleapis.com/auth/yt-analytics.readonly": "View YouTube Analytics reports for your YouTube content. This scope provides access to user activity metrics, like view counts and rating counts.",
                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": "View YouTube Analytics monetary reports for your YouTube content. This scope provides access to user activity metrics and to estimated revenue and ad performance metrics.",
                "https://www.googleapis.com/auth/youtube": "Manage your YouTube account. In the YouTube Analytics API, channel owners use this scope to manage YouTube Analytics groups and group items.",
                "https://www.googleapis.com/auth/youtubepartner": "View and manage YouTube assets and associated content on YouTube. In the YouTube Analytics API, content owners use this scope to manage YouTube Analytics groups and group items."
            }
        },
        "oauth2Token": {
            "type": "oauth2",
            "description": "OAuth2 Implicit Grant",
            "flow": "implicit",
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "name": "access_token",
            "in": "header",
            "x-response-types": [ "token" ],
            "x-custom-scheme-support": true,
            "scopes": {
                "https://www.googleapis.com/auth/yt-analytics.readonly": "View YouTube Analytics reports for your YouTube content. This scope provides access to user activity metrics, like view counts and rating counts.",
                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": "View YouTube Analytics monetary reports for your YouTube content. This scope provides access to user activity metrics and to estimated revenue and ad performance metrics.",
                "https://www.googleapis.com/auth/youtube": "Manage your YouTube account. In the YouTube Analytics API, channel owners use this scope to manage YouTube Analytics groups and group items.",
                "https://www.googleapis.com/auth/youtubepartner": "View and manage YouTube assets and associated content on YouTube. In the YouTube Analytics API, content owners use this scope to manage YouTube Analytics groups and group items."
            }
        }
    }
}
