//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using System.Collections.Generic;
using Foundations.Enums;
using System.Net;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// 
    /// </summary>
    [ServiceType(typeof(AzureTableStorage))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class AzureTableStorageQuery : OAuthRequest              
	{
        public override String Host => "https://ACCOUNTNAME.table.core.windows.net";
        public override String Path => "/{tableName}()";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        /// <summary>
        /// Schema date
        /// </summary>
        [Name("x-ms-version")]
        [ParameterType(RequestParameterType.Header)]
        [Required()]
        [DefaultFormatter()]
        public  String XMsVersion { get; set; } = "2016-05-31";
        /// <summary>
        /// Filter for the query.
        /// </summary>
        [Name("$filter")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Filter { get; set; }
        /// <summary>
        /// Select statement for the query.
        /// </summary>
        [Name("$select")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Select { get; set; }
        /// <summary>
        /// Name of the table to be queried.
        /// </summary>
        [Name("tableName")]
        [ParameterType(RequestParameterType.Path)]
        [Required()]
        [DefaultFormatter()]
        public  String TableName { get; set; }
	}
}
