//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using System.Collections.Generic;
using Foundations.Enums;
using System.Net;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// This endpoint returns metadata about a given access token
    /// </summary>
    [ServiceType(typeof(Facebook))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class FacebookTokenInfo : OAuthRequest              
	{
        public override String Host => "https://graph.facebook.com";
        public override String Path => "/v2.7/debug_token";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        public override List<String> RequiredScopes => new List<String>();
        /// <summary>
        /// The Access Token that is being inspected
        /// </summary>
        [Name("input_token")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String InputToken { get; set; }
	}
}
