//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using System.Collections.Generic;
using Foundations.Enums;
using System.Net;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure.Requests;
using Material.Infrastructure;
using Foundations.Attributes;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// Returns saved food diary entries for the user according to the filter specified
    /// </summary>
    [ServiceType(typeof(Fatsecret))]
	public partial class FatsecretMeal : OAuthRequest              
	{
        public override String Host => "http://platform.fatsecret.com";
        public override String Path => "/rest/server.api";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        /// <summary>
        /// MUST be food_entries.get
        /// </summary>
        [Name("method")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String Method { get; set; } = "food_entries.get";
        /// <summary>
        /// The number of days since January 1, 1970 (default value is the current day)
        /// </summary>
        [Name("date")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [UnixTimeDaysDateTimeFormatter()]
        public  Nullable<DateTime> Date { get; set; }
        /// <summary>
        /// The desired response format.
        /// </summary>
        [Name("format")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  FatsecretMealFormat Format { get; set; } = FatsecretMealFormat.Json;
	}
    public enum FatsecretMealFormat
    {
        [Description("xml")] Xml,
        [Description("json")] Json,
    }
}
