//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using System.Collections.Generic;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure.Requests;
using Material.Infrastructure;
using Foundations.Attributes;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// Returns a history of checkins for the authenticated user
    /// </summary>
    [ServiceType(typeof(Foursquare))]
	public partial class FoursquareCheckin : OAuthRequest              
	{
        public override String Host => "https://api.foursquare.com";
        public override String Path => "/v2/users/self/checkins";
        public override String HttpMethod => "GET";
        public override List<String> RequiredScopes => new List<String>();
        /// <summary>
        /// timestamp of the revision version of the api
        /// </summary>
        [Name("v")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String V { get; set; } = "20140806";
        /// <summary>
        /// platform context for the request
        /// </summary>
        [Name("m")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [EnumFormatter()]
        public  FoursquareCheckinM M { get; set; } = FoursquareCheckinM.Foursquare;
        /// <summary>
        /// Number of results to return, up to 250
        /// </summary>
        [Name("limit")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Limit { get; set; }
        /// <summary>
        /// The number of results to skip
        /// </summary>
        [Name("offset")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Offset { get; set; }
        /// <summary>
        /// How to sort the returned checkins
        /// </summary>
        [Name("sort")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  FoursquareCheckinSort Sort { get; set; } = FoursquareCheckinSort.Newestfirst;
        /// <summary>
        /// Retrieve the first results to follow these seconds since epoch
        /// </summary>
        [Name("afterTimestamp")]
        [ParameterType(RequestParameterType.Query)]
        [UnixTimeSecondsDateTimeFormatter()]
        public  Nullable<DateTime> AfterTimestamp { get; set; }
        /// <summary>
        /// Retrieve the first results prior to these seconds since epoch
        /// </summary>
        [Name("beforeTimestamp")]
        [ParameterType(RequestParameterType.Query)]
        [UnixTimeSecondsDateTimeFormatter()]
        public  Nullable<DateTime> BeforeTimestamp { get; set; }
	}
    public enum FoursquareCheckinM
    {
        [Description("foursquare")] Foursquare,
        [Description("swarm")] Swarm,
    }
    public enum FoursquareCheckinSort
    {
        [Description("newestfirst")] Newestfirst,
        [Description("oldestfirst")] Oldestfirst,
    }
}
