//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure.Requests;
using Material.Infrastructure;
using Foundations.Attributes;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// Converts speech into text
    /// </summary>
    [ServiceType(typeof(MicrosoftBing))]
	public partial class MicrosoftBingSpeechToText : OAuthRequest              
	{
        public override String Host => "https://speech.platform.bing.com";
        public override String Path => "/recognize";
        public override String HttpMethod => "POST";
        /// <summary>
        /// The API version being used by the client
        /// </summary>
        [Name("version")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String Version { get; set; } = "3.0";
        /// <summary>
        /// A globally unique identifier generated by the client for this request
        /// </summary>
        [Name("requestid")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  Nullable<Guid> Requestid { get; set; }
        /// <summary>
        /// A globally unique identifier used for this application
        /// </summary>
        [Name("appID")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  Nullable<Guid> AppID { get; set; } = Guid.Parse("d4d52672-91d7-4c74-8ad8-42b1d98141a5");
        /// <summary>
        /// Specifies the desired format of the returned data
        /// </summary>
        [Name("format")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String Format { get; set; } = "json";
        /// <summary>
        /// Language code of the audio content in IETF RFC 5646
        /// </summary>
        [Name("locale")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [EnumFormatter()]
        public  MicrosoftBingSpeechToTextLocale Locale { get; set; } = MicrosoftBingSpeechToTextLocale.EnUS;
        /// <summary>
        /// Operating system the client is running on. This is an open field but we encourage clients to use it consistently across devices and applications
        /// </summary>
        [Name("device.os")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [EnumFormatter()]
        public  MicrosoftBingSpeechToTextDeviceos Deviceos { get; set; } = MicrosoftBingSpeechToTextDeviceos.Unknown;
        /// <summary>
        /// The context for performing a recognition
        /// </summary>
        [Name("scenarios")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [EnumFormatter()]
        public  MicrosoftBingSpeechToTextScenarios Scenarios { get; set; } = MicrosoftBingSpeechToTextScenarios.Ulm;
        /// <summary>
        /// A globally unique device identifier of the device making the request
        /// </summary>
        [Name("instanceid")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  Nullable<Guid> Instanceid { get; set; }
	}
    public enum MicrosoftBingSpeechToTextLocale
    {
        [Description("ar-EG")] ArEG,
        [Description("en-IN")] EnIN,
        [Description("fr-FR")] FrFR,
        [Description("pt-BR")] PtBR,
        [Description("ca-ES")] CaES,
        [Description("en-NZ")] EnNZ,
        [Description("it-IT")] ItIT,
        [Description("pt-PT")] PtPT,
        [Description("da-DK")] DaDK,
        [Description("en-US")] EnUS,
        [Description("ja-JP")] JaJP,
        [Description("ru-RU")] RuRU,
        [Description("de-DE")] DeDE,
        [Description("es-ES")] EsES,
        [Description("ko-KR")] KoKR,
        [Description("sv-SE")] SvSE,
        [Description("en-AU")] EnAU,
        [Description("es-MX")] EsMX,
        [Description("nb-NO")] NbNO,
        [Description("zh-CN")] ZhCN,
        [Description("en-CA")] EnCA,
        [Description("fi-FI")] FiFI,
        [Description("nl-NL")] NlNL,
        [Description("zh-HK")] ZhHK,
        [Description("en-GB")] EnGB,
        [Description("fr-CA")] FrCA,
        [Description("pl-PL")] PlPL,
        [Description("zh-TW")] ZhTW,
    }
    public enum MicrosoftBingSpeechToTextDeviceos
    {
        [Description("Unknown")] Unknown,
        [Description("Windows OS")] WindowsOS,
        [Description("Windows Phone OS")] WindowsPhoneOS,
        [Description("XBOX")] XBOX,
        [Description("Android")] Android,
        [Description("iPhone OS")] IPhoneOS,
    }
    public enum MicrosoftBingSpeechToTextScenarios
    {
        [Description("ulm")] Ulm,
        [Description("websearch")] Websearch,
    }
}
