//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using Material.Enums;
using Material.Infrastructure;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// gets the trained model predictions for the input example
    /// </summary>
    [ServiceType(typeof(MicrosoftLuis))]
	public partial class MicrosoftLuisPredict : OAuthRequest              
	{
        public override String Host => "https://api.projectoxford.ai";
        public override String Path => "/luis/v1.0/prog/apps/{appId}/predict";
        public override String HttpMethod => "GET";
        /// <summary>
        /// The ID for the application
        /// </summary>
        [Name("appId")]
        [ParameterType(RequestParameterType.Path)]
        public  String AppId { get; set; }
        /// <summary>
        /// The example text
        /// </summary>
        [Name("example")]
        [ParameterType(RequestParameterType.Query)]
        public  String Example { get; set; }
	}
}
