//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using System.Collections.Generic;
using Foundations.Enums;
using System.Net;
using Material.Infrastructure.Requests;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure;
using Foundations.Attributes;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// Rescuetime analytic data for the user
    /// </summary>
    [ServiceType(typeof(Rescuetime))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class RescuetimeAnalyticData : OAuthRequest              
	{
        public override String Host => "https://www.rescuetime.com/";
        public override String Path => "/api/oauth/data";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        public override List<String> RequiredScopes => new List<String> { "time_data" };
        /// <summary>
        /// the format of the response
        /// </summary>
        [Name("format")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [EnumFormatter()]
        public  RescuetimeAnalyticDataFormat Format { get; set; } = RescuetimeAnalyticDataFormat.Json;
        /// <summary>
        /// 
        /// </summary>
        [Name("resolution_time")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  RescuetimeAnalyticDataResolutionTime ResolutionTime { get; set; } = RescuetimeAnalyticDataResolutionTime.Hour;
        /// <summary>
        /// organization of data
        /// </summary>
        [Name("perspective")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  RescuetimeAnalyticDataPerspective Perspective { get; set; } = RescuetimeAnalyticDataPerspective.Interval;
        /// <summary>
        /// restrict the kind of information returned
        /// </summary>
        [Name("restrict_kind")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  RescuetimeAnalyticDataRestrictKind RestrictKind { get; set; } = RescuetimeAnalyticDataRestrictKind.Efficiency;
        /// <summary>
        /// Sets the start day for data batch, inclusive (always at time 00:00, start hour/minute not supported)
        /// </summary>
        [Name("restrict_begin")]
        [ParameterType(RequestParameterType.Query)]
        [DateTimeFormatter("yyyy-MM-dd")]
        public  Nullable<DateTime> RestrictBegin { get; set; }
        /// <summary>
        /// Sets the end day for data batch, inclusive (always at time 00:00, end hour/minute not supported) 
        /// </summary>
        [Name("restrict_end")]
        [ParameterType(RequestParameterType.Query)]
        [DateTimeFormatter("yyyy-MM-dd")]
        public  Nullable<DateTime> RestrictEnd { get; set; }
	}
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum RescuetimeAnalyticDataFormat
    {
        [Description("json")] Json,
        [Description("csv")] Csv,
    }
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum RescuetimeAnalyticDataResolutionTime
    {
        [Description("month")] Month,
        [Description("week")] Week,
        [Description("day")] Day,
        [Description("hour")] Hour,
        [Description("minute")] Minute,
    }
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum RescuetimeAnalyticDataPerspective
    {
        [Description("interval")] Interval,
        [Description("rank")] Rank,
        [Description("member")] Member,
    }
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum RescuetimeAnalyticDataRestrictKind
    {
        [Description("category")] Category,
        [Description("activity")] Activity,
        [Description("productivity")] Productivity,
        [Description("overview")] Overview,
        [Description("efficiency")] Efficiency,
        [Description("document")] Document,
    }
}
