//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using System.Collections.Generic;
using Foundations.Enums;
using System.Net;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// Gets the user id, and a list of profiles (an account can have multiple genotyped people) with ids
    /// </summary>
    [ServiceType(typeof(TwentyThreeAndMe))]
	public partial class TwentyThreeAndMeUser : OAuthRequest              
	{
        public override String Host => "https://api.23andme.com";
        public override String Path => "/1/user/";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        public override List<String> RequiredScopes => new List<String> { "basic" };
        /// <summary>
        /// return what services are available to the profiles
        /// </summary>
        [Name("services")]
        [ParameterType(RequestParameterType.Path)]
        [DefaultFormatter()]
        public  Nullable<Boolean> Services { get; set; }
        /// <summary>
        /// request the email for this account
        /// </summary>
        [Name("email")]
        [ParameterType(RequestParameterType.Path)]
        [DefaultFormatter()]
        public  Nullable<Boolean> Email { get; set; }
	}
}
