//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using Material.Infrastructure.ProtectedResources;
using System;
using System.Collections.Generic;
using Foundations.Enums;
using System.Net;
using Material.Enums;
using Material.Metadata.Formatters;
using Material.Infrastructure;

namespace Material.Infrastructure.Requests
{     
    /// <summary>
    /// Get the body measures for a user
    /// </summary>
    [ServiceType(typeof(Withings))]
	public partial class WithingsWeighIn : OAuthRequest              
	{
        public override String Host => "https://wbsapi.withings.net";
        public override String Path => "/measure";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        /// <summary>
        /// the action to take (must be getmeas for this query)
        /// </summary>
        [Name("action")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String Action { get; set; } = "getmeas";
        /// <summary>
        /// the user id of the requester
        /// </summary>
        [Name("userid")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String Userid { get; set; }
        /// <summary>
        /// Returns measures updated or created after a certain date
        /// </summary>
        [Name("lastupdate")]
        [ParameterType(RequestParameterType.Query)]
        [UnixTimeSecondsDateTimeFormatter()]
        public  Nullable<DateTime> Lastupdate { get; set; }
        /// <summary>
        /// maximum number of measure groups to return
        /// </summary>
        [Name("limit")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Limit { get; set; }
        /// <summary>
        /// skip the offset most recent measure groups
        /// </summary>
        [Name("offset")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Offset { get; set; }
	}
}
