#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quantfabric.UI.Test.Android.Resource", IsApplication=true)]

namespace Quantfabric.UI.Test.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Material.Resource.String.ApplicationName = global::Quantfabric.UI.Test.Android.Resource.String.ApplicationName;
			global::Material.Resource.String.Hello = global::Quantfabric.UI.Test.Android.Resource.String.Hello;
			global::Material.Resource.String.library_name = global::Quantfabric.UI.Test.Android.Resource.String.library_name;
			global::Application.Resource.String.ApplicationName = global::Quantfabric.UI.Test.Android.Resource.String.ApplicationName;
			global::Application.Resource.String.Hello = global::Quantfabric.UI.Test.Android.Resource.String.Hello;
			global::Application.Resource.String.library_name = global::Quantfabric.UI.Test.Android.Resource.String.library_name;
			global::cbforestsharp.Droid.Resource.String.library_name = global::Quantfabric.UI.Test.Android.Resource.String.library_name;
			global::Couchbase.Lite.Android.Resource.String.library_name = global::Quantfabric.UI.Test.Android.Resource.String.library_name;
			global::Foundations.Http.Resource.String.ApplicationName = global::Quantfabric.UI.Test.Android.Resource.String.ApplicationName;
			global::Foundations.Http.Resource.String.Hello = global::Quantfabric.UI.Test.Android.Resource.String.Hello;
			global::Robotics.Mobile.Core.Resource.String.library_name = global::Quantfabric.UI.Test.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int facebookAuth = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int fatsecretAuth = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int fitbitAuth = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int foursquareAuth = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int googleAuth = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int gps = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int gridLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int linkedinAuth = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int mioalphaAuth = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int rescuetimeAuth = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int resultView = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int runkeeperAuth = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int sms = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int spotifyAuth = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int twitterAuth = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
