//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Microsoft Azure Storage REST Api 1.0.0
    /// </summary>
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class AzureTableStorage : ApiKeyResourceProvider 
    {
        public override string KeyName { get; } = "SharedKey";
        public override HttpParameterType KeyType { get; } = HttpParameterType.Header;
    }
}
