//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Fatsecret Platform API 
    /// </summary>
    [CredentialType(typeof(OAuth1Credentials))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class Fatsecret : OAuth1ResourceProvider              
	{
        public override Uri RequestUrl => new Uri("http://www.fatsecret.com/oauth/request_token");
        public override Uri AuthorizationUrl => new Uri("http://www.fatsecret.com/oauth/authorize");
        public override Uri TokenUrl => new Uri("http://www.fatsecret.com/oauth/access_token");
        public override HttpParameterType ParameterType => HttpParameterType.Body;
        public override Boolean SupportsCustomUrlScheme => true;
	}
}
