//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using System.Collections.Generic;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Google Analytics Reporting API 4
    /// </summary>
    [CredentialType(typeof(OAuth2Credentials))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class GoogleAnalytics : OAuth2ResourceProvider              
	{
        public override List<String> AvailableScopes => new List<String> { "https://www.googleapis.com/auth/analytics.readonly" };
        public override List<OAuth2ResponseType> Flows => new List<OAuth2ResponseType>();
        public override List<GrantType> GrantTypes => new List<GrantType> { GrantType.JsonWebToken };
        public override String TokenName => "Bearer";
        public override Uri TokenUrl => new Uri("https://accounts.google.com/o/oauth2/token");
	}
}
