//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using System.Collections.Generic;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Google API 1
    /// </summary>
    [CredentialType(typeof(OAuth2Credentials))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class Google  : OpenIdResourceProvider 
    {
        public override List<string> AvailableScopes { get; } = new List<string> { "https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/analytics.readonly", "openid", "openid email", "openid profile", "openid email profile" };
        public override List<OAuth2FlowType> AllowedFlows { get; } = new List<OAuth2FlowType> { OAuth2FlowType.Implicit, OAuth2FlowType.AccessCode };
        public override List<GrantType> AllowedGrantTypes { get; } = new List<GrantType> { GrantType.AuthCode, GrantType.RefreshToken };
        public override List<OAuth2ResponseType> AllowedResponseTypes { get; } = new List<OAuth2ResponseType> { OAuth2ResponseType.Token, OAuth2ResponseType.IdToken, OAuth2ResponseType.IdTokenToken, OAuth2ResponseType.Code };
        public override string TokenName { get; } = "Bearer";
        public override Uri AuthorizationUrl { get; } = new Uri("https://accounts.google.com/o/oauth2/auth");
        public override Uri TokenUrl { get; } = new Uri("https://accounts.google.com/o/oauth2/token");
        public override bool SupportsPkce { get; } = true;
        public override bool SupportsCustomUrlScheme { get; } = true;
        public override char ScopeDelimiter { get; } = ' ';
        public override Uri OpenIdDiscoveryUrl { get; } = new Uri("https://accounts.google.com/.well-known/openid-configuration");
        public override List<string> ValidIssuers { get; } = new List<string> {"https://accounts.google.com", "accounts.google.com"};
    }
}
