//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Bing API 
    /// </summary>
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class MicrosoftBing : ApiKeyExchangeResourceProvider 
    {
        public override string KeyName { get; } = "Ocp-Apim-Subscription-Key";
        public override HttpParameterType KeyType { get; } = HttpParameterType.Header;
        public override Uri TokenUrl { get; } = new Uri("https://api.cognitive.microsoft.com/sts/v1.0/issueToken");
        public override string TokenName { get; } = "Bearer";
    }
}
