//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Microsoft Project Oxford LUIS API v1.0
    /// </summary>
    [CredentialType(typeof(ApiKeyCredentials))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class MicrosoftLuis : ApiKeyResourceProvider              
	{
        public override String KeyName => "Ocp-Apim-Subscription-Key";
        public override HttpParameterType KeyType => HttpParameterType.Header;
	}
}
