//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Bing API 
    /// </summary>
    [CredentialType(typeof(ApiKeyCredentials))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class MicrosoftBing : ApiKeyExchangeResourceProvider              
	{
        public override String KeyName => "Ocp-Apim-Subscription-Key";
        public override String TokenName => "Bearer";
        public override HttpParameterType KeyType => HttpParameterType.Header;
        public override Uri TokenUrl => new Uri("https://api.cognitive.microsoft.com/sts/v1.0/issueToken");
        public override Uri OpenIdDiscoveryUrl => new Uri("https://login.microsoftonline.com/common/.well-known/openid-configuration");
	}
}
