//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using System.Collections.Generic;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;
using System.CodeDom.Compiler;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Health Graph API 
    /// </summary>
    [CredentialType(typeof(OAuth2Credentials))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class Runkeeper : OAuth2ResourceProvider              
	{
        public override List<String> AvailableScopes => new List<String>();
        public override List<OAuth2FlowType> AllowedFlows => new List<OAuth2FlowType> { OAuth2FlowType.AccessCode };
        public override List<GrantType> AllowedGrantTypes => new List<GrantType> { GrantType.AuthCode };
        public override List<OAuth2ResponseType> AllowedResponseTypes => new List<OAuth2ResponseType> { OAuth2ResponseType.Code };
        public override String TokenName => "Bearer";
        public override Uri AuthorizationUrl => new Uri("https://runkeeper.com/apps/authorize");
        public override Uri TokenUrl => new Uri("https://runkeeper.com/apps/token");
	}
}
