//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Tumblr API 2
    /// </summary>
    [CredentialType(typeof(OAuth1Credentials))]
	public partial class Tumblr : OAuth1ResourceProvider              
	{
        public override Uri RequestUrl => new Uri("https://www.tumblr.com/oauth/request_token");
        public override Uri AuthorizationUrl => new Uri("https://www.tumblr.com/oauth/authorize");
        public override Uri TokenUrl => new Uri("https://www.tumblr.com/oauth/access_token");
        public override HttpParameterType ParameterType => HttpParameterType.Body;
	}
}
