//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Metadata;
using System;
using Material.Infrastructure.Credentials;
using Foundations.HttpClient.Enums;
using Material.Infrastructure;

namespace Material.Infrastructure.ProtectedResources
{     
    /// <summary>
    /// Withings API 1.0.1
    /// </summary>
    [CredentialType(typeof(OAuth1Credentials))]
	public partial class Withings : OAuth1ResourceProvider              
	{
        public override Uri RequestUrl => new Uri("https://oauth.withings.com/account/request_token");
        public override Uri AuthorizationUrl => new Uri("https://oauth.withings.com/account/authorize");
        public override Uri TokenUrl => new Uri("https://oauth.withings.com/account/access_token");
        public override HttpParameterType ParameterType => HttpParameterType.Querystring;
	}
}
