//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Domain.Requests;
using Material.Framework.Metadata.Formatters;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// The /reports/sales resource provides comprehensive access to sales reports. Reports can be generated in a variety of formats
    /// </summary>
    [ServiceType(typeof(AppFigures))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class AppFiguresSales : OAuthRequest              
	{
        public override String Host => "https://api.appfigures.com";
        public override String Path => "/v2/reports/sales";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        /// <summary>
        /// One or more pivots separated by a comma (,). Available pivots: product, country, date, and store
        /// </summary>
        [Name("group_by")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  Nullable<AppFiguresSalesGroupBy> GroupBy { get; set; }
        /// <summary>
        /// Date, inclusive, to start reporting from. If you specify a granularity other than daily this will be rounded down to the nearest period. default: a long, long time ago.
        /// </summary>
        [Name("start_date")]
        [ParameterType(RequestParameterType.Query)]
        [DateTimeFormatter("yyyy-MM-dd")]
        public  Nullable<DateTime> StartDate { get; set; }
        /// <summary>
        /// Date, inclusive, to stop reporting. If you specify a granularity other than daily this will be rounded up to the nearset period. default: distant future
        /// </summary>
        [Name("end_date")]
        [ParameterType(RequestParameterType.Query)]
        [DateTimeFormatter("yyyy-MM-dd")]
        public  Nullable<DateTime> EndDate { get; set; }
        /// <summary>
        /// How to group dates. This affects how start_date and end_date are rounded (they snap to lower and upper barriers of the type given by this parameter) default: daily
        /// </summary>
        [Name("granularity")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  Nullable<AppFiguresSalesGranularity> Granularity { get; set; }
        /// <summary>
        /// specific products to include in the response, default: all products in account
        /// </summary>
        [Name("products")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Products { get; set; }
        /// <summary>
        /// Countries to limit the report to (can be taken from /data/countries, default: include all countries) 
        /// </summary>
        [Name("countries")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Countries { get; set; }
        /// <summary>
        /// If this is set to financial, use financial reports. This only applies to Apple products, default: none
        /// </summary>
        [Name("dataset")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  Nullable<AppFiguresSalesDataset> Dataset { get; set; }
        /// <summary>
        /// If set to true any products given in product_ids will have their children automatically selected as well. default: false) 
        /// </summary>
        [Name("include_inapps")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Boolean> IncludeInapps { get; set; }
        /// <summary>
        /// The desired response format.
        /// </summary>
        [Name("format")]
        [ParameterType(RequestParameterType.Query)]
        [EnumFormatter()]
        public  Nullable<AppFiguresSalesFormat> Format { get; set; } = AppFiguresSalesFormat.Json;
	}
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum AppFiguresSalesGroupBy
    {
        [Description("product")] Product,
        [Description("country")] Country,
        [Description("date")] Date,
        [Description("store")] Store,
    }
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum AppFiguresSalesGranularity
    {
        [Description("daily")] Daily,
        [Description("weekly")] Weekly,
        [Description("monthly")] Monthly,
        [Description("yearly")] Yearly,
    }
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum AppFiguresSalesDataset
    {
        [Description("none")] None,
        [Description("financial")] Financial,
    }
	
	[GeneratedCode("T4Toolbox", "14.0")]
    public enum AppFiguresSalesFormat
    {
        [Description("csv")] Csv,
        [Description("json")] Json,
    }
}
