//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Framework.Metadata.Formatters;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// This represents a Facebook Page. The /{page-id} node returns a single page.
    /// </summary>
    [ServiceType(typeof(Facebook))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class FacebookPage : OAuthRequest              
	{
        public override String Host => "https://graph.facebook.com";
        public override String Path => "/v2.10/{pageId}";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        public override List<String> RequiredScopes => new List<String>();
        /// <summary>
        /// Id of the page to get
        /// </summary>
        [Name("pageId")]
        [ParameterType(RequestParameterType.Path)]
        [Required()]
        [DefaultFormatter()]
        public  String PageId { get; set; }
        /// <summary>
        /// A comma seperated list of the fiels to get
        /// </summary>
        [Name("fields")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Fields { get; set; }
	}
}
