//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// Returns the Analytics data
    /// </summary>
    [ServiceType(typeof(GoogleAnalytics))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class GoogleAnalyticsReports : OAuthRequest              
	{
        public override String Host => "https://analyticsreporting.googleapis.com";
        public override String Path => "/v4/reports:batchGet";
        public override String HttpMethod => "POST";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        public override List<String> RequiredScopes => new List<String> { "https://www.googleapis.com/auth/analytics.readonly" };
	}
}
