//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Framework.Metadata.Formatters;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// gets the trained model predictions for the input example
    /// </summary>
    [ServiceType(typeof(MicrosoftLuis))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class MicrosoftLuisPredict : OAuthRequest              
	{
        public override String Host => "https://api.projectoxford.ai";
        public override String Path => "/luis/v1.0/prog/apps/{appId}/predict";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        /// <summary>
        /// The ID for the application
        /// </summary>
        [Name("appId")]
        [ParameterType(RequestParameterType.Path)]
        [Required()]
        [DefaultFormatter()]
        public  String AppId { get; set; }
        /// <summary>
        /// The example text
        /// </summary>
        [Name("example")]
        [ParameterType(RequestParameterType.Query)]
        [Required()]
        [DefaultFormatter()]
        public  String Example { get; set; }
	}
}
