//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Framework.Metadata.Formatters;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// The default response returns the first and last name, ID and URL of the authenticated user.
    /// </summary>
    [ServiceType(typeof(Pinterest))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class PinterestUser : OAuthRequest              
	{
        public override String Host => "https://api.pinterest.com";
        public override String Path => "/v1/me";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        public override List<String> RequiredScopes => new List<String> { "read_public" };
        /// <summary>
        /// The properties from the result objects to retrun
        /// </summary>
        [Name("fields")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Fields { get; set; } = "id,username,first_name,last_name,bio,created_at,counts,image";
	}
}
