//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Framework.Metadata.Formatters;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// Returns the entire profile's genome as a packed string of base pairs
    /// </summary>
    [ServiceType(typeof(TwentyThreeAndMe))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class TwentyThreeAndMeGenome : OAuthRequest              
	{
        public override String Host => "https://api.23andme.com";
        public override String Path => "/1/genomes/{profile_id}/";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        public override List<String> RequiredScopes => new List<String> { "genomes" };
        /// <summary>
        /// the profile id of the genome holder
        /// </summary>
        [Name("profile_id")]
        [ParameterType(RequestParameterType.Path)]
        [Required()]
        [DefaultFormatter()]
        public  String ProfileId { get; set; }
	}
}
