//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Framework.Metadata.Formatters;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// Get list of recent users
    /// </summary>
    [ServiceType(typeof(XamarinInsights))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class XamarinInsightsUsers : OAuthRequest              
	{
        public override String Host => "https://insights.xamarin.com";
        public override String Path => "/api/users/{appId}";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        /// <summary>
        /// Id of the app
        /// </summary>
        [Name("appId")]
        [ParameterType(RequestParameterType.Path)]
        [Required()]
        [DefaultFormatter()]
        public  String AppId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("manufacturer")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Manufacturer { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("country")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Country { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("model")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Model { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("os")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Os { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("osVersion")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String OsVersion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("search")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Search { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("appVersion")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String AppVersion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Name("time")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Time { get; set; } = 0;
        /// <summary>
        /// 
        /// </summary>
        [Name("sortColumn")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String SortColumn { get; set; } = "lastSeen";
        /// <summary>
        /// 
        /// </summary>
        [Name("SortDirection")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String SortDirection { get; set; } = "desc";
        /// <summary>
        /// 
        /// </summary>
        [Name("page")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Page { get; set; } = 0;
        /// <summary>
        /// 
        /// </summary>
        [Name("skip")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Skip { get; set; } = 0;
        /// <summary>
        /// 
        /// </summary>
        [Name("limit")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Limit { get; set; } = 20;
	}
}
