//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Material.Framework.Metadata;
using Material.Domain.ResourceProviders;
using System;
using System.Collections.Generic;
using Material.Framework.Enums;
using System.Net;
using Material.Framework.Metadata.Formatters;
using Material.Domain.Core;
using System.CodeDom.Compiler;

namespace Material.Domain.Requests
{     
    /// <summary>
    /// The Reference-Data API permits interaction with existing custom data tables associated with your company. You can use the API's GET /v2/reference-data/{dataset}/records call to return specified data loaded from other processes for targeting and personalization.
    /// </summary>
    [ServiceType(typeof(Yesmail))]
	[GeneratedCode("T4Toolbox", "14.0")]
	public partial class YesmailReferenceDataRecords : OAuthRequest              
	{
        public override String Host => "https://api.yesmail.com";
        public override String Path => "/v2/reference-data/{dataset}/records";
        public override String HttpMethod => "GET";
        public override List<MediaType> Produces => new List<MediaType> { MediaType.Json };
        public override List<MediaType> Consumes => new List<MediaType> { MediaType.Json };
        public override List<HttpStatusCode> ExpectedStatusCodes => new List<HttpStatusCode> { HttpStatusCode.OK };
        /// <summary>
        /// your company name in Yesmail application
        /// </summary>
        [Name("api-user")]
        [ParameterType(RequestParameterType.Header)]
        [Required()]
        [DefaultFormatter()]
        public  String ApiUser { get; set; }
        /// <summary>
        /// The specific {dataset} from which data is to be returned
        /// </summary>
        [Name("dataset")]
        [ParameterType(RequestParameterType.Path)]
        [Required()]
        [DefaultFormatter()]
        public  String Dataset { get; set; }
        /// <summary>
        /// The number of records to be returned with the request. Valid values are integers 0-100. The default is 25.
        /// </summary>
        [Name("limit")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Limit { get; set; }
        /// <summary>
        /// The number of rows to be bypassed by the request. Valid values are 0-any positive integer. The default is 0.
        /// </summary>
        [Name("offset")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  Nullable<Int32> Offset { get; set; }
        /// <summary>
        /// Valid values are the display names of any column in the dataset. These are filters on the set of records in the result set. Example firstname=John&postalcode=12345
        /// </summary>
        [Name("columnname")]
        [ParameterType(RequestParameterType.Query)]
        [DefaultFormatter()]
        public  String Columnname { get; set; }
	}
}
